apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`keel.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: keel
          port: 9300
