apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-cloud
  namespace: faf-ops
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: faf-ops
      secretsScope:
        projectSlug: {{.Values.infisical.projectSlug}}
        envSlug: {{.Values.infisical.envSlug}}
        secretsPath: "/grafana-cloud"
  managedSecretReference:
    secretName: grafana-cloud
    secretNamespace: faf-ops
    creationPolicy: "Owner"
