apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-phpbb3-archive
  labels:
    app: faf-phpbb3-archive
data:
  "default.conf": |-
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;
      root   /usr/share/nginx/html/;

      if ($request_uri ~ ^/(.*)\.html) {
        return 302 /$1;
      }

      location ~ \.php? {
        default_type "text/html";
        try_files $request_uri $request_uri/  =404;
      }

      # K8s healtcheck
      # Access the path. If 200 is returned, Nginx can receive requests.
      location /health {
        access_log off;
        return 200;
      }
    }
