apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ExternalName
  # Define mariadb.hostName in config, if you use an external database
  externalName: {{ default "mariadb.mariadb.svc.cluster.local" .Values.mariadb.hostName }}
