apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ergochat-webirc
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: ergochat
          port: 8097

