apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ergochat-webirc
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: ergochat
          port: 8097

---

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ergochat-irc-plain
spec:
  entryPoints:
    - irc-plain
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ergochat
          port: 6667
---

apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ergochat-irc-tls
spec:
  entryPoints:
    - irc-tls
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ergochat
          port: 6697
  tls:
    passthrough: true