{{- if not (index .Values "infisical-secret" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  ERGO__DATASTORE__MYSQL__PASSWORD: "banana"
{{- end}}
