apiVersion: v1
kind: Service
metadata:
  name: ergochat
  labels:
    app: ergochat
spec:
  selector:
    app: ergochat
  ports:
    - name: irc-plain
      port: 6667
      targetPort: 6667
    - name: irc-tls
      port: 6697
      targetPort: 6697
    - name: websocket
      port: 8097
      targetPort: 8097
