apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: dex-github
  namespace: argocd
  # TODO: Add label for app.kubernetes.io/part-of=argocd (not supported by infisical right now, do it manually!)
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: argocd
      secretsScope:
        projectSlug: {{.Values.infisical.projectSlug}}
        envSlug: {{.Values.infisical.envSlug}}
        secretsPath: "/argocd"
  managedSecretReference:
    secretName: dex-github
    secretNamespace: argocd
    creationPolicy: "Owner"