apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: dex-github
  namespace: faf-ops
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/argocd"
  managedSecretReference:
    secretName: dex-github
    secretNamespace: argocd
