apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
  labels:
    app: mariadb
data:
  "mysql.cnf": |-
    [mariadb]
    innodb_buffer_pool_instances = 4
    innodb_buffer_pool_size      = 16G

    #sql_mode = STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    # Statistics
    userstat                     = 1

    plugin_load_add = query_response_time
    query_response_time_stats = on

    # ?
    event_scheduler              = on

    # Log thicc queries
    slow_query_log               = 1

    # Increase IOPS
    innodb_io_capacity = 2000
    innodb_io_capacity_max = 5000

    # Magic Mozilla configuration
    # https://github.com/letsencrypt/openzfs-nvme-databases
    #innodb_checksum_algorithm    = none
    innodb_doublewrite           = 0
    innodb_file_per_table        = on
    innodb_log_write_ahead_size  = 16384
    innodb_use_native_aio        = 0
    innodb_use_atomic_writes     = 0
    innodb_flush_neighbors       = 0

    # Enable replication features for Debezium
    log_bin                     = mysql-bin
    binlog_format               = ROW
    binlog_row_image            = FULL
    binlog_expire_logs_seconds  = 864000