apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: Always
          name: mariadb
          ports:
            - containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: mariadb
          startupProbe:
            exec:
              command: ["mariadb-admin", "ping", "-uroot", "-h127.0.0.1"]
            periodSeconds: 10
            timeoutSeconds: 15
            initialDelaySeconds: 5
          volumeMounts:
            - name: mariadb-pvc
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/mariadb.conf.d/mysqld-custom.cnf
              subPath: mysqld-custom.cnf
            - name: config
              mountPath: /root/.my.cnf
              subPath: mysql.cnf
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: mariadb
        - name: mariadb-pvc
          persistentVolumeClaim:
            claimName: mariadb-pvc
