apiVersion: v2
name: monitoring
version: 1.0.0
dependencies:
- name: victoria-metrics-k8s-stack
  version: 0.21.1
  repository: https://victoriametrics.github.io/helm-charts/
- name: promtail
  version: 6.15.5
  repository: https://grafana.github.io/helm-charts
- name: loki
  version: 6.3.4
  repository: https://grafana.github.io/helm-charts
