{{- if not (index .Values "infisical-secret" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  ADMIN_PASSWORD: "banana"
  FAF_CLIENT_SECRET: ""
{{- end}}
