apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-user-service-hydra2
  labels:
    app: faf-user-service-hydra2
data:
  # Only for testing environments
  FAF_ENVIRONMENT: {{ eq .Values.environment "prod" | ternary "" .Values.environment }}
  REAL_IP_HEADER: "Cf-Connecting-Ip"
  PASSWORD_RESET_URL: "https://www.{{.Values.baseDomain}}/account/password/reset"
  REGISTER_ACCOUNT_URL: "https://www.{{.Values.baseDomain}}/account/register"
  ACTIVATION_URL_FORMAT: "https://user.{{.Values.baseDomain}}/register/activate?token=%s"
  FAILED_LOGIN_ACCOUNT_THRESHOLD: "5"
  FAILED_LOGIN_ATTEMPT_THRESHOLD: "10"
  FAILED_LOGIN_THROTTLING_MINUTES: "5"
  FAILED_LOGIN_DAYS_TO_CHECK: "1"
  HYDRA_TOKEN_ISSUER: "https://login.{{.Values.baseDomain}}"
  HYDRA_JWKS_URL: "https://login.{{.Values.baseDomain}}/.well-known/jwks.json"
  HYDRA_BASE_ADMIN_URL: "http://ory-hydra2:4445"
  DB_URL: "jdbc:mariadb://mariadb:3306/faf_lobby?ssl=false"
  DB_USERNAME: "faf-user-service"
  DB_DATABASE: "faf_lobby" # for mariadb init script
  LOBBY_URL: "wss://ws.{{.Values.baseDomain}}"
  IRC_TOKEN_TTL: "300"
  JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"