# This is for temporary running Ory Hydra 1.10 and 2.x in parallel.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-user-service-hydra2
  labels:
    app: faf-user-service-hydra2
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: faf-user-service-hydra2
  template:
    metadata:
      labels:
        app: faf-user-service-hydra2
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - image: faforever/faf-user-service:3.2.0-RC2
          imagePullPolicy: Always
          name: faf-user-service
          envFrom:
            - configMapRef:
                name: faf-user-service-hydra2
            - secretRef:
                name: faf-user-service
          volumeMounts:
            - name: mail-templates
              mountPath: /config/mail/
              readOnly: true
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              port: 8080
              path: /q/health
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health
            failureThreshold: 3
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: mail-templates
          configMap:
            name: faf-user-service-mail-templates
