{{- if not (index .Values "infisical-secret" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  CLIENT_SECRET: "banana"
  SESSION_SECRET: "banana"
{{- end}}
