kind: CronJob
apiVersion: batch/v1
metadata:
  name: faf-db-migrations
  namespace: faf-apps
  labels:
    app: faf-db-migrations
spec:
  # Disabled because triggered manually
  schedule: "0 0 31 2 *"
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: faf-db-migrations
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      template:
        spec:
          containers:
            - image: faforever/faf-db-migrations:v133
              imagePullPolicy: Always
              name: faf-db-migrations
              env:
                - name: FLYWAY_URL
                  value: "jdbc:mariadb://mariadb:3306/faf_lobby?ssl=false"
              envFrom:
                - secretRef:
                    name: faf-db-migrations
              args: [ "migrate" ]
          restartPolicy: Never
