apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
  namespace: postgres
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/postgres/POSTGRES_*"
  managedSecretReference:
    secretName: postgres
    secretNamespace: postgres
    creationPolicy: "Owner"
