apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
  namespace: faf-ops
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: faf-ops
      secretsScope:
        projectSlug: {{.Values.infisical.projectSlug}}
        envSlug: {{.Values.infisical.envSlug}}
        secretsPath: "/postgres/POSTGRES_*"
  managedSecretReference:
    secretName: postgres
    secretNamespace: postgres
    creationPolicy: "Owner"
