# Roles to access configMaps and secrets in all namespaces.
# This is a very dangerous role, only use it with care!
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-cm-secrets
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]