apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-init-apps-read-app-config
  namespace: faf-apps
subjects:
  - kind: ServiceAccount
    name: init-apps
    namespace: faf-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-cm-secrets