apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-replay-server
  labels:
    app: faf-replay-server
data:
  RS_CONFIG_FILE: "/config/config.yaml"
  RUST_LOG: "info"
  "config.yaml": |-
{{ tpl ( .Files.Get "config/config.yaml") . | indent 4 }}