apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: faf-replay-server
spec:
  entryPoints:
    - replay-stream
  routes:
    - match: HostSNI(`*`)
      services:
        - name: faf-replay-server
          port: 15000
