{{ if .Values.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: {{ .Values.secretNamespace }}
      secretsScope:
        projectSlug: {{.Values.projectSlug}}
        envSlug: {{.Values.envSlug}}
        secretsPath: {{ coalesce .Values.overrideSecretPath (printf "/%s" .Values.name) }}
  managedSecretReference:
    secretName: {{ .Values.name }}
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: "Owner"
  {{- end }}
