#
# Storage class for dynamic ZFS PVCs with retain policy
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-localpv
  annotations:
    # Without `ServerSideApply=true` ArgoCD fails on trying to update the resources even though nothing changed
    argocd.argoproj.io/sync-options: ServerSideApply=true
parameters:
  compression: 'off'
  dedup: 'off'
  fstype: zfs
  poolname: {{.Values.zfsPoolName}}
  recordsize: 4k
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
