apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs
  labels:
    app: wikijs
data:
  DB_TYPE: "postgres"
  DB_HOST: "postgres.faf-infra.svc"
  DB_PORT: "5432"
  DB_USER: "wikijs"
  DB_NAME: "wikijs"