apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mariadb
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/mariadb"
  managedSecretReference:
    secretName: faf-mariadb
    secretNamespace: faf-ops
    creationPolicy: "Owner"
