apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-hydra
  namespace: faf-apps
  labels:
    app: ory-hydra
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ory-hydra
  template:
    metadata:
      labels:
        app: ory-hydra
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      containers:
        - image: oryd/hydra:v2.3.0
          imagePullPolicy: Always
          name: ory-hydra
          envFrom:
            - configMapRef:
                name: ory-hydra
            - secretRef:
                name: ory-hydra
          ports:
            - containerPort: 4444
            - containerPort: 4445
          args: [ "serve", "all", "--dangerous-force-http"]
      restartPolicy: Always