{{- if not (index .Values "infisical-secret" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  BRACKMAN_DISCORD_SECRET: "banana"
  DB_PASSWORD: "banana"
  DSN: "postgres://hydra:banana@postgres:5432/ory-hydra"
  FAF_QAI_SECRET: "banana"
  SECRETS_SYSTEM: "bananabananabananabanana"
{{- end}}
