kind: Job
apiVersion: batch/v1
metadata:
  name: ory-hydra-migration
  namespace: faf-apps
  labels:
    app: ory-hydra-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '-1'
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: ory-hydra-migration
          envFrom:
            - configMapRef:
                name: ory-hydra
            - secretRef:
                name: ory-hydra
          ports:
            - containerPort: 4444
            - containerPort: 4445
          args: [ "migrate", "sql", "--read-from-env", "--yes"]
      restartPolicy: Never
