# =======================================
# Jesus, what the fuck is happening here?
# =======================================
#
# 1. Create a service account
# 2. Permit it to read configmaps and secrets in the faf-apps namespace
# 3. Iterate over the databasesAndUsers list and create a job for each database
#    a) initContainer: Load the configmap and secret into environment variables. This must happen via k8s api, as we can't directly reference cm/secrets cross-namespace.
#    b) actual container: Load the env from file and create the database and user

{{- $wave := 1 }}
{{- range .Values.databasesAndUsers }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-sync-db-user-{{ $wave }}
  labels:
    app: mongodb-sync-db-user
    argocd.argoproj.io/instance: mongodb
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '{{ $wave }}'
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: init-apps
      volumes:
        - name: config # We will store the apps config for database, username and password here
          emptyDir: {}
      initContainers:
        - name: load-config
          image: alpine/kubectl
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              mkdir -p /config

              echo -n "SYNC_DATABASE=" > /config/env
              kubectl get cm {{ .configMapRef }} \
                -n faf-apps \
                -o jsonpath='{.data.{{ .databaseKey }}}' >> /config/env
              echo >> /config/env

              echo -n "SYNC_USERNAME=" >> /config/env
              kubectl get cm {{ .configMapRef }} \
                -n faf-apps \
                -o jsonpath='{.data.{{ .usernameKey }}}' >> /config/env
              echo >> /config/env

              echo -n "SYNC_PASSWORD=" >> /config/env
              kubectl get secret {{ .secretRef }} \
                -n faf-apps \
                -o jsonpath='{.data.{{ .passwordKey }}}' \
                | base64 -d >> /config/env
              echo >> /config/env
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: mongodb-sync-db-user
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mongodb
            - configMapRef:
                name: mongodb
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -a
              . /config/env
              set +a

              ADMIN_USER=$MONGO_INITDB_ROOT_USERNAME
              ADMIN_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

              mongo_exec() {
                mongosh --quiet --host mongodb.faf-infra.svc --username "$ADMIN_USER" --password "$ADMIN_PASSWORD" --authenticationDatabase admin --eval "$@"
              }

              result=$(mongo_exec "db.getSiblingDB(\"$SYNC_DATABASE\").getUser(\"$SYNC_USERNAME\");")
              if [ "$result" != "null" ]; then
                  echo "User $SYNC_USERNAME exists"
              else
                  mongo_exec "db.getSiblingDB(\"${SYNC_DATABASE}\").createUser( { user: \"${SYNC_USERNAME}\", pwd: \"${SYNC_PASSWORD}\", roles: [ \"readWrite\" ] } );"
                  mongo_exec "db.getSiblingDB(\"${SYNC_DATABASE}\").grantRolesToUser(\"${SYNC_USERNAME}\",[{ role: \"clusterMonitor\", db: \"admin\" }]);"
                  echo "Created User $SYNC_USERNAME"
              fi

          volumeMounts:
            - name: config
              mountPath: /config
      restartPolicy: Never
{{- $wave = add $wave 1 }}
{{- end }}
