{{- if not (index .Values "infisical-secret" "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: "banana"
  NODEBB_PASSWORD: "banana"
{{- end}}
