apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - image: pgautoupgrade/pgautoupgrade:17-bookworm
          name: upgrade-postgres
          env:
            - name: PGAUTO_ONESHOT
              value: "yes"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data/

      restartPolicy: Always
      containers:
        - image: postgres:17.6-bookworm
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres
            - secretRef:
                name: postgres
          startupProbe:
            exec:
              command: ["pg_isready", "-Uroot", "-h127.0.0.1"]
            periodSeconds: 5
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: config
          configMap:
            name: postgres
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
