# =======================================
# Jesus, what the fuck is happening here?
# =======================================
#
# 1. Create a service account
# 2. Permit it to read configmaps and secrets in the faf-apps namespace
# 3. Iterate over the databasesAndUsers list and create a job for each database
#    a) initContainer: Load the configmap and secret into environment variables. This must happen via k8s api, as we can't directly reference cm/secrets cross-namespace.
#    b) actual container: Load the env from file and create the database and user

{{- $wave := 1 }}
{{- range .Values.users }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-sync-user-{{ $wave }}
  labels:
    app: rabbitmq-sync-user
    argocd.argoproj.io/instance: rabbitmq
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: '{{ $wave }}'
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: init-apps
      volumes:
        - name: config # We will store the apps config for database, username and password here
          emptyDir: {}
      initContainers:
        - name: load-config
          image: alpine/kubectl
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              mkdir -p /config

              echo -n "SYNC_USERNAME=" >> /config/env
              kubectl get cm {{ .configMapRef }} \
                -n faf-apps \
                -o jsonpath='{.data.{{ .usernameKey }}}' >> /config/env
              echo >> /config/env

              echo -n "SYNC_PASSWORD=" >> /config/env
              kubectl get secret {{ .secretRef }} \
                -n faf-apps \
                -o jsonpath='{.data.{{ .passwordKey }}}' \
                | base64 -d >> /config/env
              echo >> /config/env
          volumeMounts:
            - name: config
              mountPath: /config
      containers:
        - name: rabbitmq-sync-db-user
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbitmq
            - configMapRef:
                name: rabbitmq
          command: ["/bin/sh", "-c"]
          args: 
            - |
              set -a
              . /config/env
              set +a

              vhost="/faf-core"

              rabbitmq_admin_exec() {
                rabbitmqadmin --format=bash --host=rabbitmq-0.rabbitmq.faf-apps.svc.cluster.local --username=$ADMIN_USER --password=$ADMIN_PASSWORD "$@"
              }

              if rabbitmq_admin_exec list vhosts | grep -q "$vhost"; then
                echo "$vhost vhost already exists"
              else
                rabbitmq_admin_exec declare vhost name="$vhost" 
              fi

              if rabbitmq_admin_exec list users | grep -q "$SYNC_USERNAME"; then
                echo "$SYNC_USERNAME user alerady exists"
              else
                rabbitmq_admin_exec declare user name="$SYNC_USERNAME" password="$SYNC_PASSWORD" tags=""
              fi

              rabbitmq_admin_exec declare permission vhost="$vhost" user="$SYNC_USERNAME" configure=".*" read=".*" write=".*"

          volumeMounts:
            - name: config
              mountPath: /config
      restartPolicy: Never
{{- $wave = add $wave 1 }}
{{- end }}
