# This is a temporary workaround to point to the RabbitMQ instance running in faf-stack
# (it is exposed to the host though)
# TODO: Replace as soon as rabbitmq runs in cluster
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ExternalName
  externalName: {{.Values.hostName}}
