apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3.13.7-management-alpine
          imagePullPolicy: Always
          name: rabbitmq
          ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 15672
              name: webinterface
              protocol: TCP
            - containerPort: 15692
              name: prometheus
              protocol: TCP
          startupProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 15
            timeoutSeconds: 15
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: rabbitmq
            - configMapRef:
                name: rabbitmq
          volumeMounts:
            - name: rabbitmq-pvc
              mountPath: /var/lib/rabbitmq
            - name: config
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: config
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq_conf
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: rabbitmq
        - name: rabbitmq-pvc
          persistentVolumeClaim:
            claimName: rabbitmq-pvc