apiVersion: v2
name: replay-mounter
version: 1.0.0
description: CIFS/SMB mount watchdog for the faf-replays hostPath PV

dependencies:
  - name: infisical-secret
    version: 1.0.0
    repository: file://../../common/infisical-secret
