apiVersion: v1
kind: ConfigMap
metadata:
  name: ory-hydra2
  namespace: faf-apps
  labels:
    app: ory-hydra2
data:
  URLS_SELF_ISSUER: "https://login.{{.Values.baseDomain}}"
  URLS_LOGIN: "https://user-nx.{{.Values.baseDomain}}/oauth2/login"
  URLS_CONSENT: "https://user-nx.{{.Values.baseDomain}}/oauth2/consent"
  STRATEGIES_ACCESS_TOKEN: "jwt"
  OAUTH2_CLIENT_CREDENTIALS_DEFAULT_GRANT_ALLOWED_SCOPE: "true"
  # These are only used for postgres init script, it is redundant in the DSN secret! Don't forget to also create a secret for DB_PASSWORD
  DB_USER: "hydra"
  DB_NAME: "ory-hydra"
