apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ory-hydra2
  namespace: faf-apps
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: faf-ops
      secretsScope:
        projectSlug: {{.Values.infisical.projectSlug}}
        envSlug: {{.Values.infisical.envSlug}}
        secretsPath: "/ory-hydra2"
  managedSecretReference:
    secretName: ory-hydra2
    secretNamespace: faf-apps
    creationPolicy: "Owner"
