apiVersion: v1
kind: Service
metadata:
  name: ory-hydra2
  namespace: faf-apps
  labels:
    app: ory-hydra2
spec:
  selector:
    app: ory-hydra2
  ports:
    - name: public-port
      port: 4444
      targetPort: 4444
    - name: admin-port
      port: 4445
      targetPort: 4445
