apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ExternalName
  # Define postgres.hostName in config, if you use an external database
  externalName: {{ default "mariadb.faf-infra.svc.cluster.local" .Values.mariadb.hostName }}
