apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodebb
  name: nodebb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      initContainers:
        - name: permission-init
          image: alpine:3.16.0
          volumeMounts:
            - mountPath: /data/uploads
              name: nodebb
              subPath: uploads
      containers:
        - image: ghcr.io/nodebb/nodebb:3.10.3
          imagePullPolicy: Always
          name: nodebb
          command:
            - sh
            - -c
            - sleep 10000
          volumeMounts:
            - mountPath: /usr/src/app/config.json
              name: config
              subPath: config.json
            - mountPath: /usr/src/app/node_modules
              name: nodebb
              subPath: node_modules
            - mountPath: /usr/src/app/build
              name: nodebb
              subPath: build
            - mountPath: /usr/src/app/public/uploads
              name: nodebb
              subPath: uploads
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: nodebb
        - name: nodebb
          persistentVolumeClaim:
            claimName: nodebb-pvc
      securityContext:
        fsGroup: 1001