apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodebb
  name: nodebb
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodebb
  template:
    metadata:
      labels:
        app: nodebb
    spec:
      initContainers:
        - name: permission-init
          image: alpine/git
          command:
            - sh
            - -c
{{/*          FOR SSO PLUGIN DEVELOPMENT ONLY: (afterwards still needs rebuild&restart from admin panel) */}}
{{/*            - git clone https://github.com/FAForever/nodebb-plugin-sso-oauth-faforever /data/plugins/sso-faforever && chown -R 1001:1001 /data/* && chmod 775 /data/* && ls -lah /data*/}}
            - chown -R 1001:1001 /data/* && chmod 775 /data/* && ls -lah /data
          volumeMounts:
            - mountPath: /data/node_modules
              name: nodebb
              subPath: node_modules
            - mountPath: /data/build
              name: nodebb
              subPath: build
            - mountPath: /data/uploads
              name: nodebb
              subPath: uploads
            - mountPath: /data/plugins
              name: plugins
      containers:
        - image: ghcr.io/nodebb/nodebb:3.12.4
          imagePullPolicy: Always
          name: nodebb
          volumeMounts:
            - mountPath: /opt/config/config.json
              name: config
              subPath: config.json
            - mountPath: /usr/src/app/node_modules
              name: nodebb
              subPath: node_modules
            - mountPath: /usr/src/app/build
              name: nodebb
              subPath: build
            - mountPath: /usr/src/app/public/uploads
              name: nodebb
              subPath: uploads
{{/*          FOR SSO PLUGIN DEVELOPMENT ONLY: (afterwards still needs rebuild&restart from admin panel) */}}
{{/*            - mountPath: /usr/src/app/local-plugins*/}}
{{/*              name: plugins*/}}
{{/*          lifecycle:*/}}
{{/*            postStart:*/}}
{{/*              exec:*/}}
{{/*                command: [npm i -f --prefix /usr/src/app/local-plugins/sso-faforever && npm i /usr/src/app/local-plugins/sso-faforever]*/}}
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: nodebb
        - name: nodebb
          persistentVolumeClaim:
            claimName: nodebb-pvc
        - name: plugins
          emptyDir: {}
      securityContext:
        fsGroup: 1001