apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ExternalName
  # Define mariadb.hostName in config, if you use an external database
  externalName: {{ default "postgres.postgres.svc.cluster.local" .Values.postgres.hostName }}
