apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: debezium
  namespace: faf-apps
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-apps
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/debezium"
  managedSecretReference:
    secretName: debezium
    secretNamespace: faf-apps
    creationPolicy: "Owner"

