apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-lobby-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lobby.{{.Values.baseDomain}}`) || Host(`ws.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: faf-lobby-server
          port: 8003
