apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: faf-lobby-server
  namespace: faf-apps
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-apps
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/faf-lobby-server"
  managedSecretReference:
    secretName: faf-lobby-server
    secretNamespace: faf-apps
    creationPolicy: "Owner"
