apiVersion: v1
kind: Service
metadata:
  name: faf-lobby-server
  labels:
    app: faf-lobby-server
spec:
  selector:
    app: faf-lobby-server
  ports:
    - name: websocket
      port: 8003
      targetPort: 8003
    - name: metrics
      port: 8011
      targetPort: 8011
