apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-telemetry-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ice-telemetry.{{.Values.baseDomain}}`)`)
      kind: Rule
      services:
        - name: faf-telemetry-server
          port: 8080
