name: Checks

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  checks:

    runs-on: ubuntu-latest
    container:
      image: docker/tilt:latest

    steps:
      - uses: actions/checkout@v6

      - uses: azure/setup-helm@v5.0.0

      - name: Create k8s Kind Cluster
        run: ctlptl create cluster kind --registry=ctlptl-registry

      - name: Cache Helm Output
        id: cache-helm-output
        uses: actions/cache@v5
        with:
          path: .helm-cache
          key: ${{ github.ref_name }}
          restore-keys: |
            develop
            ${{ github.base_ref }}

      - name: Test Using Local Config
        run: tilt ci --timeout "5m"

      - name: List images
        run: |
            registry_host=$(ctlptl get cluster kind-kind -o template --template '{{.status.localRegistryHosting.host}}')
            kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" \
            | tr -s '[[:space:]]' '\n' \
            | sort \
            | uniq \
            | grep -Ev "(registry.k8s.io|docker.io|:latest|:main)" \
            | grep ":.*$" \
            | while IFS= read -r line; do
                  docker image pull $line
                  docker image save $line -o .image-cache/${line//\//-}.tar
              done
            docker image list
      
