apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-api
  labels:
    app: faf-api
data:
  # MailJet healtcheck fails non-stop
  MANAGEMENT_HEALTH_MAIL_ENABLED: false

  FAF_DOMAIN: "{{.Values.baseDomain}}"
  JAVA_TOOL_OPTIONS: "-Xms1024m -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError"

  # App options
  DATABASE_ADDRESS: "mariadb"
  DATABASE_NAME: "faf_lobby"
  DATABASE_USERNAME: "faf-java-api"
  EMAIL_FROM_ADDRESS: "admin@faforever.com"
  EMAIL_FROM_NAME: "FAForever"
  {{ if ne .Values.environment "prod" }}
  GITHUB_DEPLOYMENT_ENVIRONMENT: "development"
  {{ end }}
  LEAGUE_DATABASE_ADDRESS: "mariadb"
  LEAGUE_DATABASE_NAME: "faf-league"
  LEAGUE_DATABASE_USERNAME: "faf-java-api"
  NODEBB_BASE_URL: "http://nodebb:4567"
  NODEBB_USER_ID: "1"
  RECAPTCHA_ENABLED: "true"
  RABBIT_HOST: rabbitmq
  RABBIT_USERNAME: faf-api
  REPLAY_DOWNLOAD_URL_FORMAT: https://content.{{.Values.baseDomain}}/replays/%s
  # temporary bugfix until faf-java-api >3.4.5
  MOD_PREVIEW_URL_FORMAT: https://content.{{.Values.baseDomain}}/mods/thumbs/%s
  MINIMUM_DAYS_BETWEEN_USERNAME_CHANGE: "90"
  USERNAME_RESERVATION_TIME_IN_MONTHS: "3"
