apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  labels:
    app: grafana
data:
  GF_SERVER_ROOT_URL: https://grafana.{{.Values.baseDomain}}
  # 1 refers to org id 1 (default main org)
  GITHUB_ORG_MAPPING: "@FAForever/gitops-argocd:1:Admin @FAForever/grafana-editor-{{ .Values.environment }}:1:Editor @FAForever/grafana-viewer-{{ .Values.environment }}:1:Viewer"
