apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana
  namespace: faf-ops
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/grafana"
  managedSecretReference:
    secretName: grafana
    secretNamespace: faf-ops
    creationPolicy: "Owner"
