# Unlike kube-prometheus-stack, VM doesn't automatically scrape services that have the prometheus labels set
# Thanks to copying and pasting from GitHub issues, we can easily workaround the problem

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: services
spec:
  discoveryRole: "endpoints"
  jobLabel: "app.kubernetes.io/name"
  endpoints:
    - port: metrics
      relabelConfigs:
        - sourceLabels:
            [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels:
            [__meta_kubernetes_service_annotation_prometheus_io_scheme]
          action: replace
          targetLabel: __scheme__
          regex: (https?)
        - sourceLabels:
            [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            [
              __address__,
              __meta_kubernetes_service_annotation_prometheus_io_port,
            ]
          action: replace
          targetLabel: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
  namespaceSelector:
    any: true
  selector: {}