apiVersion: apps/v1
kind: Deployment
metadata:
  name: faf-coop-deployer
  labels:
    app: faf-coop-deployer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: faf-coop-deployer
  template:
    metadata:
      labels:
        app: faf-coop-deployer
    spec:
      containers:
        - name: faf-coop-deployer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: faf-coop-deployer
            - secretRef:
                name: faf-coop-deployer
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
