{{- if .Values.localSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: faf-coop-deployer
stringData:
  DATABASE_URL: {{ .Values.localSecret.databaseUrl | quote }}
  PATCH_VERSION: {{ .Values.localSecret.patchVersion | default "latest" | quote }}
{{- end }}
