apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
  annotations:
    reloader.stakater.com/auto: "true"
    keel.sh/trigger: poll
    keel.sh/policy: force
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          imagePullPolicy: Always
          name: wordpress
          envFrom:
            - configMapRef:
                name: wordpress
            - secretRef:
                name: wordpress
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            # This also mounts installed plugins from disk! There might be a better way to do this.
            - name: data
              mountPath: /var/www/html/wp-content/
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wordpress-pvc