apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: wordpress
  namespace: faf-apps
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-apps
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/wordpress"
  managedSecretReference:
    secretName: wordpress
    secretNamespace: faf-apps
    creationPolicy: "Owner"
