apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: wordpress
  namespace: faf-apps
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: faf-ops
      secretsScope:
        projectSlug: {{.Values.infisical.projectSlug}}
        envSlug: {{.Values.infisical.envSlug}}
        secretsPath: "/wordpress"
  managedSecretReference:
    secretName: wordpress
    secretNamespace: faf-apps
    creationPolicy: "Owner"
